services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    hostname: unbound
    volumes:
      - ./unbound:/opt/unbound/etc/unbound/
    networks:
      private_network:
        ipv4_address: ${IP_UNBOUND}
    env_file:
      - .env

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    networks:
      private_network:
        ipv4_address: ${IP_WG}
    depends_on:
      - unbound
      - pihole
    ports:
      - "${PORT_WG}:51820/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    cap_drop:
      - ALL
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
    volumes:
      - ./wireguard:/config
    env_file:
      - .env

  wg-sidecar:
    build:
      context: .
      dockerfile: sidecar/Dockerfile.sidecar
    container_name: wg_sidecar
    restart: unless-stopped
    network_mode: "service:wireguard"   
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN                      
    cap_drop:
      - ALL
    volumes:
      - ./wireguard:/config             
    environment:
      - SIDECAR_TOKEN=${SIDECAR_TOKEN}
    env_file:
      - .env

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    depends_on:
      - unbound
    ports:
      - "65231:80/tcp"
    hostname: pihole
    dns:
      - ${IP_UNBOUND}
      - 127.0.0.1
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    networks:
      private_network:
        ipv4_address: ${IP_PIHOLE}
    env_file:
      - .env
    environment:
      TZ: ${DETECTED_TZ}
      WEBPASSWORD: ${WEB_PASSWORD}
      PIHOLE_DNS_: "${IP_UNBOUND}#5053"

  auth-service:
    build:
      context: .
      dockerfile: auth/Dockerfile.auth
      args:
        APP_PORT: ${PORT_AUTH}
    container_name: auth_service
    restart: unless-stopped
    depends_on:
      - wg-sidecar
    networks:
      private_network:
        ipv4_address: ${IP_AUTH}        
    environment:
      - SIDECAR_URL=http://${IP_SIDECAR}:${PORT_SIDECAR}
      - SIDECAR_TOKEN=${SIDECAR_TOKEN}
    env_file:
      - .env

  nginx-proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - auth-service
    networks:
      private_network:
        ipv4_address: ${IP_NGINX}

networks:
  private_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.144.0/24