FROM python:3.12-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends wireguard-tools iproute2 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app
RUN pip install --no-cache-dir -r requirements.txt

ENV PORT_SIDECAR=${PORT_SIDECAR}

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port ${PORT_SIDECAR}"]
